// <auto-generated />
using ITQTestApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITQTestApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITQTestApp.Domain.Entities.ReferenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReferenceItems");
                });

            modelBuilder.Entity("ITQTestApp.Domain.Entities.ReferenceItem", b =>
                {
                    b.OwnsOne("ITQTestApp.Domain.ValueObjects.Code", "Code", b1 =>
                        {
                            b1.Property<int>("ReferenceItemId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("code");

                            b1.HasKey("ReferenceItemId");

                            b1.ToTable("ReferenceItems");

                            b1.WithOwner()
                                .HasForeignKey("ReferenceItemId");
                        });

                    b.Navigation("Code")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
